[2023-01-14T14:36:58.100+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2023-01-14T14:22:50.915243+00:00 [queued]>
[2023-01-14T14:36:58.128+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2023-01-14T14:22:50.915243+00:00 [queued]>
[2023-01-14T14:36:58.129+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-14T14:36:58.131+0000] {taskinstance.py:1284} INFO - Starting attempt 3 of 3
[2023-01-14T14:36:58.132+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-14T14:36:58.172+0000] {taskinstance.py:1304} INFO - Executing <Task(HttpSensor): is_api_available> on 2023-01-14 14:22:50.915243+00:00
[2023-01-14T14:36:58.185+0000] {standard_task_runner.py:55} INFO - Started process 36894 to run task
[2023-01-14T14:36:58.219+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'manual__2023-01-14T14:22:50.915243+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp9ba0sten']
[2023-01-14T14:36:58.234+0000] {standard_task_runner.py:83} INFO - Job 52: Subtask is_api_available
[2023-01-14T14:36:58.426+0000] {task_command.py:389} INFO - Running <TaskInstance: user_processing.is_api_available manual__2023-01-14T14:22:50.915243+00:00 [running]> on host 35e95982c619
[2023-01-14T14:36:58.623+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2023-01-14T14:22:50.915243+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-14T14:22:50.915243+00:00
[2023-01-14T14:36:58.626+0000] {http.py:122} INFO - Poking: api/
[2023-01-14T14:36:58.647+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-01-14T14:36:58.651+0000] {http.py:150} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2023-01-14T14:36:58.979+0000] {base.py:228} INFO - Success criteria met. Exiting.
[2023-01-14T14:36:59.000+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20230114T142250, start_date=20230114T143658, end_date=20230114T143659
[2023-01-14T14:36:59.067+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2023-01-14T14:36:59.123+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
